# Generated by Django 4.2.14 on 2024-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=10)),
                (
                    "price_per_share",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("number_of_shares", models.IntegerField()),
                ("transaction_date", models.DateField()),
                (
                    "broker_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
